//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataaccessXML2TXT
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_RegimenFiscal
    {
        public double c_RegimenFiscal1 { get; set; }
        public string Descripcion { get; set; }
        public string Física { get; set; }
        public string Moral { get; set; }
    }
}
