//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataaccessXML2TXT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_DatosFijosPorEmpleado
    {
        public int fijoPorEmpId { get; set; }
        public string rfcEmpleado { get; set; }
        public string Sindicalizado { get; set; }
        public string c_TipoJornada { get; set; }
        public string Departamento { get; set; }
        public string c_RiesgoPuesto { get; set; }
        public string c_Banco { get; set; }
        public string CuentaBancaria { get; set; }
        public string c_Estado { get; set; }
    }
}
