//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataaccessXML2TXT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_Deduccion
    {
        public int deduccionId { get; set; }
        public Nullable<int> nominaId { get; set; }
        public string TipoDeduccion { get; set; }
        public Nullable<double> c_TipoDeduccion { get; set; }
        public string Clave { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Importe { get; set; }
    
        public virtual c_TipoDeduccion c_TipoDeduccion1 { get; set; }
        public virtual TE_Nomina TE_Nomina { get; set; }
    }
}
