//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataaccessXML2TXT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_Nomina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TE_Nomina()
        {
            this.TE_Incapacidad = new HashSet<TE_Incapacidad>();
            this.TE_JubilacionPensionRetiro = new HashSet<TE_JubilacionPensionRetiro>();
            this.TE_OtroPago = new HashSet<TE_OtroPago>();
            this.TE_Percepcion = new HashSet<TE_Percepcion>();
            this.TE_Receptor_Subcontratacion = new HashSet<TE_Receptor_Subcontratacion>();
            this.TE_SeparacionIndemnizacion = new HashSet<TE_SeparacionIndemnizacion>();
            this.TE_Deduccion = new HashSet<TE_Deduccion>();
        }
    
        public int nominaId { get; set; }
        public string version { get; set; }
        public string c_TipoNomina { get; set; }
        public string FechaPago { get; set; }
        public string FechaInicialPago { get; set; }
        public string FechaFinalPago { get; set; }
        public Nullable<decimal> NumDiasPagados { get; set; }
        public Nullable<decimal> TotalPercepciones { get; set; }
        public Nullable<decimal> TotalDeducciones { get; set; }
        public Nullable<decimal> TotalOtrosPagos { get; set; }
        public string Emisor_CURP { get; set; }
        public string Emisor_RegistroPatronal { get; set; }
        public string Emisor_RfcPatronOrigen { get; set; }
        public string Emisor_EntidadSNCF_c_OrigenRecurso { get; set; }
        public Nullable<decimal> Emisor_EntidadSNCF_MontoRecursoPropio { get; set; }
        public string Receptor_CURP { get; set; }
        public string Receptor_NumSeguridadSocial { get; set; }
        public string Receptor_FechaInicioRelLaboral { get; set; }
        public string Receptor_Antiguedad { get; set; }
        public Nullable<double> Receptor_c_TipoContrato { get; set; }
        public string Receptor_Sindicalizado { get; set; }
        public Nullable<double> Receptor_c_TipoJornada { get; set; }
        public string Receptor_TipoRegimen { get; set; }
        public Nullable<double> Receptor_c_TipoRegimen { get; set; }
        public string Receptor_NumEmpleado { get; set; }
        public string Receptor_Departamento { get; set; }
        public string Receptor_Puesto { get; set; }
        public Nullable<double> Receptor_c_RiesgoPuesto { get; set; }
        public string Receptor_PeriodicidadPago { get; set; }
        public Nullable<double> Receptor_c_PeriodicidadPago { get; set; }
        public Nullable<double> Receptor_c_Banco { get; set; }
        public string Receptor_CuentaBancaria { get; set; }
        public Nullable<decimal> Receptor_SalarioBaseCotApor { get; set; }
        public Nullable<decimal> Receptor_SalarioDiarioIntegrado { get; set; }
        public string Receptor_c_ClaveEntFed { get; set; }
        public Nullable<decimal> Percepciones_TotalSueldos { get; set; }
        public Nullable<decimal> Percepciones_TotalSeparacionIndemnizacion { get; set; }
        public Nullable<decimal> Percepciones_TotalJubilacionPensionRetiro { get; set; }
        public Nullable<decimal> Percepciones_TotalGravado { get; set; }
        public Nullable<decimal> Percepciones_TotalExento { get; set; }
        public Nullable<decimal> Deducciones_TotalOtrasDeducciones { get; set; }
        public Nullable<decimal> Deducciones_TotalImpuestosRetenidos { get; set; }
    
        public virtual c_Banco c_Banco { get; set; }
        public virtual c_Estado c_Estado { get; set; }
        public virtual c_OrigenRecurso c_OrigenRecurso { get; set; }
        public virtual c_PeriodicidadPago c_PeriodicidadPago { get; set; }
        public virtual c_RiesgoPuesto c_RiesgoPuesto { get; set; }
        public virtual c_TipoContrato c_TipoContrato { get; set; }
        public virtual c_TipoJornada c_TipoJornada { get; set; }
        public virtual c_TipoNomina c_TipoNomina1 { get; set; }
        public virtual c_TipoRegimen c_TipoRegimen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TE_Incapacidad> TE_Incapacidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TE_JubilacionPensionRetiro> TE_JubilacionPensionRetiro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TE_OtroPago> TE_OtroPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TE_Percepcion> TE_Percepcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TE_Receptor_Subcontratacion> TE_Receptor_Subcontratacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TE_SeparacionIndemnizacion> TE_SeparacionIndemnizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TE_Deduccion> TE_Deduccion { get; set; }
    }
}
