//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataaccessXML2TXT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_Percepcion_HorasExtra
    {
        public int horasextraId { get; set; }
        public Nullable<int> percepcionId { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<double> c_TipoHoras { get; set; }
        public Nullable<int> HorasExtra { get; set; }
        public Nullable<decimal> ImportePagado { get; set; }
        public string TipoHoras { get; set; }
    
        public virtual c_TipoHoras c_TipoHoras1 { get; set; }
        public virtual TE_Percepcion TE_Percepcion { get; set; }
    }
}
