//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataaccessXML2TXT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_Percepcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TE_Percepcion()
        {
            this.TE_Percepcion_HorasExtra = new HashSet<TE_Percepcion_HorasExtra>();
        }
    
        public int percepcionId { get; set; }
        public Nullable<int> nominaId { get; set; }
        public string TipoPercepcion { get; set; }
        public Nullable<double> c_TipoPercepcion { get; set; }
        public string Clave { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> ImporteGravado { get; set; }
        public Nullable<decimal> ImporteExcento { get; set; }
        public Nullable<decimal> AccionesOTitulos_ValorMercado { get; set; }
        public Nullable<decimal> AccionesOTitulos_PrecioAlOtorgarse { get; set; }
        public Nullable<bool> bolExclude { get; set; }
    
        public virtual c_TipoPercepcion c_TipoPercepcion1 { get; set; }
        public virtual TE_Nomina TE_Nomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TE_Percepcion_HorasExtra> TE_Percepcion_HorasExtra { get; set; }
    }
}
