//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataaccessXML2TXT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_RfcTimbrado
    {
        public int timbradoKey { get; set; }
        public string txtRFC { get; set; }
        public string txtNombre { get; set; }
        public string txtFechaPago { get; set; }
        public string txtFechaInicialPago { get; set; }
        public string txtFechaFinalPago { get; set; }
        public string fechaTimbrado { get; set; }
        public string numDiasPagados { get; set; }
        public string txtTotalPercepciones { get; set; }
        public string txtTotalDeducciones { get; set; }
        public string totalOtrosPagos { get; set; }
        public string txtPeriodo { get; set; }
        public string txtUUID { get; set; }
        public string txtFileName { get; set; }
    }
}
