//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataaccessXML2TXT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_Receptor_Subcontratacion
    {
        public int subcontratacionId { get; set; }
        public int nominaId { get; set; }
        public string RfcLabora { get; set; }
        public Nullable<decimal> PorcentajeTiempo { get; set; }
    
        public virtual TE_Nomina TE_Nomina { get; set; }
    }
}
