//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataaccessXML2TXT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_TXT_HEADER
    {
        public int headerId { get; set; }
        public string H1_05 { get; set; }
        public string H1_08 { get; set; }
        public string H1_11 { get; set; }
        public string H1_14 { get; set; }
        public string H1_30 { get; set; }
        public string H1_31 { get; set; }
        public string H1_32 { get; set; }
        public string H1_46 { get; set; }
        public string H1_50 { get; set; }
        public string H2_02 { get; set; }
        public string H2_03 { get; set; }
        public string H2_05 { get; set; }
        public string H2_06 { get; set; }
        public string H2_08 { get; set; }
        public string H2_09 { get; set; }
        public string H2_11 { get; set; }
        public string H2_12 { get; set; }
        public string H2_13 { get; set; }
        public string H2_14 { get; set; }
        public string H4_02 { get; set; }
        public string H4_03 { get; set; }
        public string H4_13 { get; set; }
        public string S_10 { get; set; }
        public string S_16 { get; set; }
        public string S_37 { get; set; }
        public string D_04 { get; set; }
        public string D_06 { get; set; }
        public string D_07 { get; set; }
        public string D_09 { get; set; }
        public string D_25 { get; set; }
        public string D_37 { get; set; }
        public string D_38 { get; set; }
        public string D_42 { get; set; }
        public string S_36 { get; set; }
    }
}
