//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataaccessXML2TXT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_UUID2CANCEL
    {
        public int cancelKey { get; set; }
        public string Emisor_RFC { get; set; }
        public string Receptor_rfc { get; set; }
        public string Receptor_nombre { get; set; }
        public string PeriodicidadPago { get; set; }
        public string FechaFinalPago { get; set; }
        public string UUID { get; set; }
    }
}
